version: '3.3'

networks:
  backend:
services:
  leitourapi:
    container_name: containerleitour
    image: leitourapi:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7770:80"

    depends_on:
      - database

  database:
    container_name: database_leitour
    image: mysql:5.7
    ports:
      - 1234:3306
    expose:
      - 1234
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_leitour
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345678   
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db-volume:/var/lib/mysql/

     

volumes:
  db-volume: