version: '3.3'

networks:
  backend:
services:
  leitourapi:
    container_name: containerleitour
    image: leitourapi:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DOCKER_RUNNING: 'true'
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_leitour
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678

    depends_on:
      - mysql

  mysql:
    container_name: database_leitour
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_leitour
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345678

volumes:
  db-volume:
